version: '3'
services:
    webapi:
      build:
        context: .
        dockerfile: api.Dockerfile
      ports:
        - "8000:80"
    blazorserver:
      build:
        context: .
        dockerfile: server.Dockerfile
      ports:
        - "5000:80"
      depends_on:
        - webapi
    blazorwasm:
      build:
        context: .
        dockerfile: wasm.Dockerfile
      ports:
        - "4000:80"
      depends_on:
        - webapi